kf = 3.5;
Tf = 0.5;
Hf = tf(kf,[Tf,1,0]);
wf = 1/Tf;
suprareglaj = 0.1;
tita = -log(suprareglaj)/sqrt(pi^2+log(suprareglaj)^2);
modA = 1/4/sqrt(2)/tita^2;
modAdb = db(modA);
F = kf/wf/sqrt(1+Tf^2*wf^2);
Fdb = db(F);
FN = Fdb-modAdb;
kp = 10^(-FN/20);
bode(kp*Hf);
wt1 = 1.22;
ts = 2/wt1/tita^2;
ts_impus = 2;
wt2 = ts/ts_impus*wt1;
tau_d = Tf;
kpd = kp*wt2/wt1;
Tn = tau_d*ts_impus/ts;
Hpd = kpd*tf([tau_d,1],[Tn,1]);
Ho = feedback(Hpd*Hf,1);
figure,step(Ho);
t = 0:0.01:10;
figure(), plot(t,t,t,lsim(Ho,t,t));
cv = 2*wt2*tita/2/tita;
dwb = 2*wt2*tita*sqrt(1-2*tita+sqrt(2-4*tita^2+4*tita^4));